# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright IBM Corp All Rights Reserved
# SPDX-License-Identifier: Apache-2.0

SRCMOUNT = "/hyperledger"
$script = <<SCRIPT
set -x

cd #{SRCMOUNT}/fabric/devenv
./setup.sh

SCRIPT

Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "../..", "#{SRCMOUNT}"
  config.vm.synced_folder "../..", "/opt/gopath/src/github.com/hyperledger"
  config.vm.synced_folder "../../../kchristidis/island", "/opt/gopath/src/github.com/kchristidis/island"
  config.disksize.size = '20GB'
  config.vm.provider :virtualbox do |vb|
    vb.name = "hyperledger"
    vb.customize ['modifyvm', :id, '--memory', '4096']
    vb.cpus = 2
  end
  config.vm.provision :shell, inline: $script
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" # https://github.com/hashicorp/vagrant/issues/1673#issuecomment-28288042
end
